// Generates a branded NutraPack Proof cover sheet and optionally merges it
// with an uploaded PDF. Uses pdf-lib (browser-compatible, no server needed).
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

const ACCENT  = rgb(1, 0.357, 0.122);   // #ff5b1f
const INK     = rgb(0.078, 0.067, 0.051); // #14110d
const MUTED   = rgb(0.608, 0.584, 0.541); // #9b958a
const HAIRLINE= rgb(0.831, 0.816, 0.792); // #d4cfc9

export async function buildProofPDF({ jobTitle, customer, uploadedBy, date, fileName, logoUrl }) {
  const doc   = await PDFDocument.create();
  const page  = doc.addPage([612, 792]); // US Letter
  const { width, height } = page.getSize();

  const bold   = await doc.embedFont(StandardFonts.HelveticaBold);
  const regular= await doc.embedFont(StandardFonts.Helvetica);

  // --- Header bar -----------------------------------------------------------
  page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: INK });

  // Try to embed the logo image if a URL is provided
  if (logoUrl) {
    try {
      const res  = await fetch(logoUrl);
      const buf  = await res.arrayBuffer();
      const img  = await doc.embedPng(buf).catch(() => doc.embedJpg(buf).catch(() => null));
      if (img) {
        const dim = img.scaleToFit(36, 36);
        page.drawImage(img, { x: 36, y: height - 58, width: dim.width, height: dim.height });
      }
    } catch (_) { /* logo failed to load — skip silently */ }
  }

  // "NUTRAPACK" wordmark
  page.drawText("NUTRAPACK", {
    x: 84, y: height - 50,
    size: 20, font: bold, color: rgb(1, 1, 1),
  });

  // Orange accent pill — "PROOF"
  page.drawRectangle({ x: width - 120, y: height - 62, width: 84, height: 28, color: ACCENT });
  page.drawText("PROOF", {
    x: width - 101, y: height - 50,
    size: 13, font: bold, color: rgb(1, 1, 1),
  });

  // --- Main heading ---------------------------------------------------------
  page.drawText("NutraPack Proof", {
    x: 48, y: height - 130,
    size: 28, font: bold, color: INK,
  });

  // Horizontal rule
  page.drawLine({ start: { x: 48, y: height - 148 }, end: { x: width - 48, y: height - 148 }, thickness: 1, color: HAIRLINE });

  // --- Job details ----------------------------------------------------------
  const rows = [
    ["Job title",    jobTitle   || "—"],
    ["Customer",     customer   || "—"],
    ["File",         fileName   || "—"],
    ["Uploaded by",  uploadedBy || "—"],
    ["Date",         date       || new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })],
  ];

  let y = height - 188;
  for (const [lab, val] of rows) {
    page.drawText(lab, { x: 48, y, size: 10, font: regular, color: MUTED });
    page.drawText(val, { x: 180, y, size: 11, font: bold, color: INK });
    y -= 28;
  }

  // --- Notice box -----------------------------------------------------------
  y -= 16;
  page.drawRectangle({ x: 48, y: y - 52, width: width - 96, height: 66, color: rgb(0.976, 0.976, 0.969), borderColor: HAIRLINE, borderWidth: 1 });
  page.drawText("PROOF — NOT FOR PRODUCTION USE", { x: 60, y: y - 16, size: 9, font: bold, color: ACCENT });
  page.drawText("Review this proof carefully before approving. Check all text, colors, dimensions,", { x: 60, y: y - 29, size: 9, font: regular, color: MUTED });
  page.drawText("and placement. Once approved, NutraPack will proceed to production.", { x: 60, y: y - 41, size: 9, font: regular, color: MUTED });

  // --- Approval signature line ---------------------------------------------
  const sigY = 160;
  page.drawLine({ start: { x: 48, y: sigY + 30 }, end: { x: width - 48, y: sigY + 30 }, thickness: 0.5, color: HAIRLINE });
  page.drawText("APPROVAL", { x: 48, y: sigY + 40, size: 8, font: bold, color: MUTED });

  const cols = [
    { label: "Approved by (print name)", x: 48,          w: 180 },
    { label: "Signature",                x: 240,         w: 160 },
    { label: "Date",                     x: 420,         w: 110 },
    { label: "Approved  □   Changes required  □", x: 48, w: 500 },
  ];
  let colRow = 0;
  for (const col of cols) {
    const cy = colRow < 3 ? sigY - 4 : sigY - 36;
    if (colRow === 3) {
      page.drawText(col.label, { x: col.x, y: cy, size: 9, font: regular, color: INK });
    } else {
      page.drawLine({ start: { x: col.x, y: cy }, end: { x: col.x + col.w, y: cy }, thickness: 0.5, color: INK });
      page.drawText(col.label, { x: col.x, y: cy - 12, size: 8, font: regular, color: MUTED });
    }
    colRow++;
  }

  // Footer
  page.drawText(`Generated by NutraPack App · ${new Date().toISOString().slice(0, 10)}`, {
    x: 48, y: 32, size: 8, font: regular, color: MUTED,
  });

  return doc.save(); // returns Uint8Array
}

// Merges the cover sheet as page 1 of an existing PDF blob.
export async function mergeCoverWithPDF(coverBytes, proofBlob) {
  const proofBytes = new Uint8Array(await proofBlob.arrayBuffer());
  const coverDoc   = await PDFDocument.load(coverBytes);
  const proofDoc   = await PDFDocument.load(proofBytes);

  const merged   = await PDFDocument.create();
  const [cover]  = await merged.copyPages(coverDoc, [0]);
  merged.addPage(cover);
  const proofPages = await merged.copyPages(proofDoc, proofDoc.getPageIndices());
  proofPages.forEach((p) => merged.addPage(p));

  return merged.save();
}
