// GENERATED by scripts/build-panel-engine.mjs from public/tools/panel-builder.html
// (source sha256 da1a3e4a182f6bdd). Do not edit: change the builder, then re-run the script.
/* eslint-disable */
// @ts-nocheck
import { shims } from "./panel-engine-shims.js";
const { state, window, LIBS, needLib, renderImport, renderAll, closeImport, toast, fontAvailable, measure, loadProfiles } = shims;

/* ---------- reference data ---------- */
const MACROS = [
  {k:'calories', label:'Calories', unit:'', dv:null, round:'cal', indent:0},
  {k:'totalFat', label:'Total Fat', unit:'g', dv:78, round:'fat', indent:0, pct:true},
  {k:'satFat', label:'Saturated Fat', unit:'g', dv:20, round:'fat', indent:1, pct:true},
  {k:'transFat', label:'Trans Fat', unit:'g', dv:null, round:'fat', indent:1},
  {k:'cholesterol', label:'Cholesterol', unit:'mg', dv:300, round:'chol', indent:0, pct:true},
  {k:'totalCarb', label:'Total Carbohydrate', unit:'g', dv:275, round:'g', indent:0, pct:true},
  {k:'fiber', label:'Dietary Fiber', unit:'g', dv:28, round:'g', indent:1, pct:true},
  {k:'totalSugars', label:'Total Sugars', unit:'g', dv:null, round:'g', indent:1},
  {k:'addedSugars', label:'Added Sugars', unit:'g', dv:50, round:'g', indent:2, pct:true},
  {k:'protein', label:'Protein', unit:'g', dv:50, round:'g', indent:0, pct:false}
];
const VM = [
  ['vitA','Vitamin A','mcg',900],['vitC','Vitamin C','mg',90],['vitD','Vitamin D','mcg',20],['vitE','Vitamin E','mg',15],
  ['vitK','Vitamin K','mcg',120],['thiamin','Thiamin','mg',1.2],['riboflavin','Riboflavin','mg',1.3],['niacin','Niacin','mg',16],
  ['vitB6','Vitamin B6','mg',1.7],['folate','Folate','mcg',400],['vitB12','Vitamin B12','mcg',2.4],['biotin','Biotin','mcg',30],
  ['pantothenic','Pantothenic Acid','mg',5],['choline','Choline','mg',550],['calcium','Calcium','mg',1300],['iron','Iron','mg',18],
  ['phosphorus','Phosphorus','mg',1250],['iodine','Iodine','mcg',150],['magnesium','Magnesium','mg',420],['zinc','Zinc','mg',11],
  ['selenium','Selenium','mcg',55],['copper','Copper','mg',0.9],['manganese','Manganese','mg',2.3],['chromium','Chromium','mcg',35],
  ['molybdenum','Molybdenum','mcg',45],['chloride','Chloride','mg',2300],['sodium','Sodium','mg',2300],['potassium','Potassium','mg',4700],
  ['fluoride','Fluoride','mg',null]
].map((a,i)=>({k:a[0],label:a[1],unit:a[2],dv:a[3],order:i}));
const VMK = Object.fromEntries(VM.map(v=>[v.k,v]));
const FONTS = {
  'Myriad Pro':{css:'"Myriad Pro"',ps:{r:'MyriadPro-Regular',b:'MyriadPro-Bold',i:'MyriadPro-It',bi:'MyriadPro-BoldIt'}},
  'Myriad Pro Condensed':{css:'"Myriad Pro Cond","Myriad Pro Condensed"',ps:{r:'MyriadPro-Cond',b:'MyriadPro-BoldCond',i:'MyriadPro-CondIt',bi:'MyriadPro-BoldCondIt'}},
  'Myriad Pro Semi Condensed':{css:'"Myriad Pro SemiCond","Myriad Pro Semi Condensed"',ps:{r:'MyriadPro-SemiCn',b:'MyriadPro-BoldSemiCn',i:'MyriadPro-SemiCnIt',bi:'MyriadPro-BoldSemiCnIt'}},
  'Helvetica Neue':{css:'"Helvetica Neue"',ps:{r:'HelveticaNeue',b:'HelveticaNeue-Bold',i:'HelveticaNeue-Italic',bi:'HelveticaNeue-BoldItalic'}},
  'Helvetica Neue LT Std Condensed':{css:'"Helvetica Neue LT Std","HelveticaNeueLTStd-Cn"',ps:{r:'HelveticaNeueLTStd-Cn',b:'HelveticaNeueLTStd-BdCn',i:'HelveticaNeueLTStd-CnO',bi:'HelveticaNeueLTStd-BdCnO'}},
  'Helvetica':{css:'Helvetica',ps:{r:'Helvetica',b:'Helvetica-Bold',i:'Helvetica-Oblique',bi:'Helvetica-BoldOblique'}},
  'Arial':{css:'Arial',ps:{r:'ArialMT',b:'Arial-BoldMT',i:'Arial-ItalicMT',bi:'Arial-BoldItalicMT'}},
  'Arial Narrow':{css:'"Arial Narrow"',ps:{r:'ArialNarrow',b:'ArialNarrow-Bold',i:'ArialNarrow-Italic',bi:'ArialNarrow-BoldItalic'}},
  'Acumin Pro':{css:'"Acumin Pro"',ps:{r:'AcuminPro-Regular',b:'AcuminPro-Bold',i:'AcuminPro-Italic',bi:'AcuminPro-BoldItalic'}},
  'Acumin Pro Condensed':{css:'"Acumin Pro Condensed"',ps:{r:'AcuminProCond-Regular',b:'AcuminProCond-Bold',i:'AcuminProCond-Italic',bi:'AcuminProCond-BoldItalic'}},
  'Futura PT':{css:'"Futura PT"',ps:{r:'FuturaPT-Book',b:'FuturaPT-Bold',i:'FuturaPT-BookObl',bi:'FuturaPT-BoldObl'}},
  'Custom':null
};
const PROCESS = {digital:{label:'Digital',minRule:0.25,minType:4},flexo:{label:'Flexo',minRule:0.5,minType:4.5},direct:{label:'Direct print (can/bottle)',minRule:0.5,minType:5}};
const CATEGORIES = ['excipient','flavor','sweetener','acid','color','capsule','preservative','other'];
const FALLBACK = ', "Helvetica Neue", Arial, sans-serif';
const CAPSULE_MG = {'000':163,'00':118,'0':96,'1':76,'2':61,'3':48,'4':38};

/* ---------- helpers ---------- */
const uid = ()=>Math.random().toString(36).slice(2,9);
const esc = s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const num = v=>{const n=parseFloat(v);return Number.isFinite(n)?n:null};
const trim = (n,d=3)=>String(+Number(n).toFixed(d));
function toMg(v,unit){ if(v==null) return null; unit=String(unit||'mg'); if(unit.startsWith('mcg')) return v/1000; if(unit==='g') return v*1000; return v; }
function inDvUnit(v,unit,dvUnit){ const mg=toMg(v,unit); return dvUnit==='mcg'? mg*1000 : mg; }
function roundTo(v,step){ return Math.round(v/step)*step; }
function baseText(){ return {titleCase:'title', servingBold:true, servingColon:false, amtHead:'Amount Per Serving', dvHead:'% Daily Value', carbLabel:'Total Carbohydrate', pctSym:'*', pctNote:'Percent Daily Values are based on a 2,000 calorie diet.', daggerNote:'Daily Value not established.', unitSpace:true, naKRound:true, boldNames:false, flavorMix:'Natural & Artificial Flavors', containsUpper:false, oiLabel:'Other Ingredients:', sfDisclaimer:true}; }
function baseStyle(){ return {family:'Myriad Pro', custom:{css:'',r:'',b:'',i:'',bi:''}, titleFamily:'same', titleStyle:'b', fitTitle:true, titleSize:18, body:7, head:6.5, foot:6, lead:1.12, rowPad:0.7, widthIn:2.4, pad:3, colGap:4, indent:5, box:0.5, heavy:5, medium:2.5, hair:0.35, rowRules:true, groupBars:true, inverse:false, oiSize:6.5, oiGap:6, showOI:true}; }
function baseMacros(){ const m={}; MACROS.forEach(x=>m[x.k]={v:null,status:'missing',show:'auto'}); return m; }
const R = (o)=>Object.assign({id:uid(), status:'verified', note:'', noteSev:'info', tm:'', tmStatus:'n/a', allergen:''}, o);
function blankProject(){
  return {id:uid(), name:'Untitled product', coman:'', client:'', ref:'', form:'capsule', serving:{qty:'2', unit:'Capsules', weight:null, pattern:'unit', spc:'30', showSpc:true},
    pkg:{area:null, areaSource:'estimated', process:'digital'}, allergensReviewed:false, macros:baseMacros(), rows:[], flags:[],
    suggested:{qty:'2 capsules', liquid:'', timing:'', freq:'daily', override:''}, callouts:[], text:baseText(), style:baseStyle()};
}
const P = ()=>state.projects[state.cur];

/* ---------- text ---------- */
function fontDef(p, which){
  const S=p.style;
  let fam = which==='title' && S.titleFamily!=='same' ? S.titleFamily : S.family;
  if(fam==='Custom'){ const c=S.custom; return {name:c.css||'Custom', css:c.css?`"${c.css}"`:'sans-serif', ps:{r:c.r||'Custom-Regular', b:c.b||c.r||'Custom-Bold', i:c.i||c.r||'Custom-Italic', bi:c.bi||c.b||'Custom-BoldItalic'}}; }
  const f = FONTS[fam]||FONTS['Myriad Pro']; return {name:fam, css:f.css, ps:f.ps};
}
function measureSegs(f, segs, size){ return segs.reduce((a,s)=>a+measure(f,s,size),0); }
function parseMarkup(s, base={}){
  const out=[]; const re=/(\*\*[^*]+\*\*|_[^_]+_)/g; let last=0, m;
  s=String(s||'');
  while((m=re.exec(s))){ if(m.index>last) out.push({text:s.slice(last,m.index), b:!!base.b, i:!!base.i});
    const tok=m[0]; if(tok.startsWith('**')) out.push({text:tok.slice(2,-2), b:true, i:!!base.i}); else out.push({text:tok.slice(1,-1), b:!!base.b, i:true}); last=m.index+tok.length; }
  if(last<s.length) out.push({text:s.slice(last), b:!!base.b, i:!!base.i});
  return out.filter(x=>x.text);
}
const plain = s=>String(s||'').replace(/\*\*|_/g,'');
function wrapSegs(f, segs, size, maxW, contIndent){
  // words are runs of non-space text that may span style changes, e.g. "(" + italic "Aframomum"
  const words=[]; let cur=null;
  segs.forEach(s=>{ s.text.split(/(\s+)/).forEach(part=>{ if(part==='') return;
    if(/^\s+$/.test(part)){ cur=null; words.push({space:true, pieces:[{text:' ',b:s.b,i:s.i}]}); return; }
    if(!cur){ cur={space:false, pieces:[]}; words.push(cur); }
    cur.pieces.push({text:part,b:s.b,i:s.i}); }); });
  const wW=w=>w.pieces.reduce((a,pc)=>a+measure(f,pc,size),0);
  const lines=[]; let line=[], w=0, limit=maxW;
  for(const wd of words){
    if(wd.space){ if(line.length){ line.push(wd); w+=wW(wd);} continue; }
    const ww=wW(wd);
    if(line.length && w+ww>limit){ while(line.length && line[line.length-1].space) line.pop(); lines.push(line); line=[]; w=0; limit=maxW-contIndent; }
    line.push(wd); w+=ww;
  }
  while(line.length && line[line.length-1].space) line.pop();
  if(line.length) lines.push(line);
  return lines.map(l=>{ const m=[]; l.forEach(wd=>wd.pieces.forEach(s=>{ const pr=m[m.length-1]; if(pr && pr.b===s.b && pr.i===s.i) pr.text+=s.text; else m.push({text:s.text,b:s.b,i:s.i}); })); return m; });
}

/* ---------- rules ---------- */
function roundMacro(kind, v){
  if(v==null) return null;
  if(kind==='cal'){ if(v<5) return 0; if(v<=50) return roundTo(v,5); return roundTo(v,10); }
  if(kind==='g'){ if(v<0.5) return 0; if(v<1) return '<1'; return Math.round(v); }
  if(kind==='fat'){ if(v<0.5) return 0; if(v<5) return roundTo(v,0.5); return Math.round(v); }
  if(kind==='chol'){ if(v<2) return 0; if(v<5) return '<5'; return roundTo(v,5); }
  return v;
}
function roundNaK(v){ if(v<5) return 0; if(v<=140) return roundTo(v,5); return roundTo(v,10); }
function pctText(p){ if(p==null) return ''; if(p>0 && p<1) return '<1%'; return Math.round(p).toLocaleString('en-US')+'%'; }
function amtStr(p, v, unit){ const sp=p.text.unitSpace?' ':''; if(v==='' || v==null) return ''; return `${typeof v==='number'?trim(v):v}${unit?sp+unit:''}`; }
function childrenOf(p, gid){ return p.rows.filter(r=>(r.kind==='ingredient'||r.kind==='group') && (r.parent||'')===gid); }
function groupSumMg(p, gid){ let s=0; for(const c of childrenOf(p,gid)){ if(c.kind==='group') s+=groupSumMg(p,c.id); else s+=toMg(num(c.amt)||0,c.unit)||0; } return s; }
function fmtTotal(p, mg){ if(mg>=1000) return amtStr(p, +trim(mg/1000,3), 'g'); return amtStr(p, +trim(mg,2), 'mg'); }
function parseAmt(s){ const m=String(s||'').match(/([\d.]+)\s*(mcg|mg|g)\b/i); return m?{v:parseFloat(m[1]),u:m[2].toLowerCase()}:null; }
function computePanel(p){
  const T=p.text, rowsTop=[], rowsDI=[];
  let pctUsed=false, daggerUsed=false;
  // macros
  for(const m of MACROS){
    const e=p.macros[m.k]; if(!e) continue;
    const rv = roundMacro(m.round, num(e.v));
    const isZero = rv===0 || rv==null;
    let show = e.show==='show' ? true : e.show==='hide' ? false : (!isZero);
    if(e.v==null && e.show!=='show') show=false;
    if(!show) continue;
    let label = m.k==='totalCarb' ? T.carbLabel : m.label;
    let amount = m.k==='calories' ? String(rv??0) : amtStr(p, rv??0, m.unit);
    let name = label;
    if(m.k==='addedSugars'){ name = `Includes ${amtStr(p, rv??0, 'g')} Added Sugars`; amount=''; }
    let dv='';
    if(m.dv && m.pct!==false){ const base = rv==='<1'?Math.min(num(e.v)||0.99,0.99):(typeof rv==='number'?rv:0); dv=pctText(base/m.dv*100); if(dv) { dv+=T.pctSym; pctUsed=true; } }
    rowsTop.push({key:'m_'+m.k, segs:[{text:name,b:false,i:false}], amount, dv, indent:m.indent, macro:m.k});
  }
  // vitamins & minerals
  const nuts = p.rows.filter(r=>r.kind==='nutrient' && VMK[r.nk]).slice().sort((a,b)=>(VMK[a.nk]?.order??99)-(VMK[b.nk]?.order??99));
  for(const r of nuts){
    const def=VMK[r.nk]; let v=num(r.amt);
    if(T.naKRound && (r.nk==='sodium'||r.nk==='potassium') && v!=null) v=roundNaK(v);
    const label = r.label || def.label;
    let segs=[{text:label, b:T.boldNames, i:false}];
    if(r.source && r.place!=='other'){ segs=segs.concat(parseMarkup(` (${r.conn&&r.conn!=='none'?r.conn+' ':''}${r.source})`)); }
    let dv='';
    if(def.dv && v!=null){ dv=pctText(inDvUnit(v, r.unit, def.unit)/def.dv*100); }
    else { dv='†'; daggerUsed=true; }
    rowsTop.push({key:r.id, rowId:r.id, segs, amount:amtStr(p, v, r.unit), dv, indent:0});
  }
  // dietary ingredients (tree order)
  const walk=(gid,depth)=>{
    for(const r of childrenOf(p,gid)){
      if(r.kind==='group'){
        let total='';
        if(r.showTotal){ total = r.override ? r.override.replace(/\s+/g, T.unitSpace?' ':'') : fmtTotal(p, groupSumMg(p,r.id)); }
        const top = depth===0;
        if(top) daggerUsed=true;
        rowsDI.push({key:r.id, rowId:r.id, segs:parseMarkup(r.name,{b:top}), amount:total, amountBold:top, dv:top?'†':'', indent:depth, group:true, top});
        walk(r.id, depth+1);
      } else {
        const dv = depth===0 ? '†' : '';
        if(dv) daggerUsed=true;
        rowsDI.push({key:r.id, rowId:r.id, segs:parseMarkup(r.name), amount:amtStr(p, num(r.amt), r.unit), dv, indent:depth, top:depth===0});
      }
    }
  };
  walk('',0);
  const foot=[];
  if(pctUsed) foot.push(T.pctSym+T.pctNote);
  if(daggerUsed) foot.push('†'+T.daggerNote);
  return {rowsTop, rowsDI, foot, pctUsed, daggerUsed};
}
function otherIngredients(p){
  const T=p.text; const items=[]; const flav=[];
  for(const r of p.rows){
    if(r.kind==='other'){
      if(r.cat==='flavor'){ flav.push(r); continue; }
      let name=r.name; if(r.cat==='color' && !/\(color\)/i.test(name)) name+=' (color)';
      items.push({name, w:num(r.input), rowId:r.id});
    } else if(r.kind==='nutrient' && r.source && r.place==='other'){
      items.push({name:r.source, w:num(r.input), rowId:r.id});
    }
  }
  if(flav.length){
    const types=new Set(flav.map(f=>f.ftype||'unconfirmed'));
    const hasArt = types.has('artificial')||types.has('nat_art');
    const hasNat = types.has('natural')||types.has('unconfirmed')||types.has('nat_art');
    let label = hasArt&&hasNat ? T.flavorMix : hasArt ? (flav.length>1?'Artificial Flavors':'Artificial Flavor') : (flav.length>1?'Natural Flavors':'Natural Flavor');
    const w = flav.reduce((a,f)=>a+(num(f.input)||0),0);
    items.push({name:label, w: flav.some(f=>num(f.input)==null)?null:w, flavor:true, members:flav.map(f=>f.id)});
  }
  items.sort((a,b)=>(b.w??-1)-(a.w??-1));
  const allergens=[...new Set(p.rows.map(r=>(r.allergen||'').trim()).filter(Boolean))];
  let contains = allergens.length ? 'Contains: '+allergens.join(', ') : '';
  if(contains && T.containsUpper) contains = contains.toUpperCase();
  return {items, text: items.map(i=>i.name).join(', ')+(items.length?'.':''), contains};
}
function suggestedUse(p){
  const s=p.suggested; if(s.override && s.override.trim()) return {text:s.override.trim(), auto:false, missing:[]};
  const missing=[]; let t='';
  if(p.form==='powder'){
    const liquid = s.liquid || (missing.push('water volume'),'[__ fl oz]');
    t = `Mix ${s.qty||'one serving'} with ${liquid} of water`;
    if(s.timing) t+=` and consume ${s.timing}`; t+='.';
  } else {
    t = `As a dietary supplement, take ${s.qty||'one serving'}${s.freq?' '+s.freq:''} with water`;
    if(s.timing) t+=`, ${s.timing}`; t+='.';
    if(!s.freq) missing.push('frequency');
  }
  return {text:t, auto:true, missing};
}
function totalCaffeine(p){ let mg=0, n=0; for(const r of p.rows){ if(r.kind==='ingredient' && num(r.caff)){ mg+=(toMg(num(r.amt),r.unit)||0)*num(r.caff)/100; n++; } } return {mg:Math.round(mg), n}; }

/* ---------- panel ---------- */
function layout(p){
  const S=p.style, T=p.text, f=fontDef(p,'body'), tf=fontDef(p,'title');
  const W=S.widthIn*72, pad=S.pad, x0=pad, xr=W-pad, inner=W-2*pad;
  const items=[]; const rowY={};
  const panel=computePanel(p);
  let y=pad;
  const rule=(h,grp)=>{ if(h<=0) return; items.push({t:'rect',x:x0,y,w:inner,h,grp}); y+=h; };
  // title
  const title = T.titleCase==='upper'?'SUPPLEMENT FACTS':'Supplement Facts';
  const tseg=[{text:title,b:S.titleStyle==='b',i:false}];
  let ts = S.titleSize;
  if(S.fitTitle){ const w1=measureSegs(tf,tseg,10); ts = Math.min(40, 10*inner/w1); }
  y += ts*0.74;
  items.push({t:'text',x:x0,y,segs:tseg,size:ts,font:'title',grp:'Title'});
  y += ts*0.2;
  // serving
  const sv=p.serving; const sp=T.unitSpace?' ':'';
  const wStr = sv.weight? `${trim(sv.weight,2)}${sp}g` : '';
  let servText = sv.pattern==='weight_approx' ? `${wStr} (Approx. ${sv.qty}${sv.unit?' '+sv.unit:''})` : sv.pattern==='unit_weight' && wStr ? `${sv.qty} ${sv.unit} (${wStr})` : `${sv.qty} ${sv.unit}`.trim();
  const colon=T.servingColon?':':'';
  const servLines=[[{text:`Serving Size${colon} `,b:T.servingBold,i:false},{text:servText,b:false,i:false}]];
  if(sv.showSpc && sv.spc) servLines.push([{text:`Servings Per Container${colon} `,b:T.servingBold,i:false},{text:String(sv.spc),b:false,i:false}]);
  const lh=S.body*S.lead;
  servLines.forEach((segs,i)=>{ const wr=wrapSegs(f,segs,S.body,inner,S.indent); wr.forEach(l=>{ y+=lh; items.push({t:'text',x:x0,y:y-lh*0.22,segs:l,size:S.body,grp:i?'Servings_Per_Container':'Serving_Size'}); }); });
  y += lh*0.25;
  rule(S.heavy,'Bar_Heavy_Top');
  // column widths
  const allRows=[...panel.rowsTop,...panel.rowsDI];
  const dvHeadSeg=[{text:T.dvHead,b:true,i:false}], amtHeadSeg=[{text:T.amtHead,b:true,i:false}];
  let dvW = measureSegs(f,dvHeadSeg,S.head);
  let amtW = 0;
  allRows.forEach(r=>{ dvW=Math.max(dvW, measure(f,{text:r.dv,b:false,i:false},S.body)); amtW=Math.max(amtW, measure(f,{text:r.amount,b:!!r.amountBold,i:false},S.body)); });
  const dvRight = xr, amtRight = xr - dvW - S.colGap;
  const nameMax = amtRight - amtW - S.colGap - x0;
  // header row
  const hh=S.head*S.lead + S.rowPad*2;
  const hb = y + S.rowPad + S.head*0.8;
  items.push({t:'text',x:amtRight,y:hb,segs:amtHeadSeg,size:S.head,anchor:'end',grp:'Header'});
  items.push({t:'text',x:dvRight,y:hb,segs:dvHeadSeg,size:S.head,anchor:'end',grp:'Header'});
  y += hh;
  rule(S.medium,'Bar_Medium_Header');
  const drawRow=(r)=>{
    const ind = r.indent*S.indent;
    const lines = wrapSegs(f, r.segs, S.body, nameMax-ind, S.indent*0.8);
    const top=y; const h = S.rowPad*2 + Math.max(1,lines.length)*lh;
    const grp = 'Row_'+(r.macro||plain(r.segs.map(s=>s.text).join('')).replace(/[^A-Za-z0-9]+/g,'_').slice(0,32));
    lines.forEach((l,i)=>{ const by = top + S.rowPad + S.body*0.8 + i*lh; items.push({t:'text',x:x0+ind+(i?S.indent*0.8:0),y:by,segs:l,size:S.body,grp,row:r.rowId}); });
    const by0 = top + S.rowPad + S.body*0.8;
    if(r.amount) items.push({t:'text',x:amtRight,y:by0,segs:[{text:r.amount,b:!!r.amountBold,i:false}],size:S.body,anchor:'end',grp,row:r.rowId});
    if(r.dv) items.push({t:'text',x:dvRight,y:by0,segs:[{text:r.dv,b:false,i:false}],size:S.body,anchor:'end',grp,row:r.rowId});
    if(r.rowId) rowY[r.rowId]=top+h/2; if(r.macro) rowY['m_'+r.macro]=top+h/2;
    y += h;
  };
  panel.rowsTop.forEach((r,i)=>{ if(i && S.rowRules) rule(S.hair,'Hairline'); drawRow(r); });
  if(panel.rowsDI.length){
    if(panel.rowsTop.length) rule(S.heavy,'Bar_Heavy_Section');
    panel.rowsDI.forEach((r,i)=>{ if(i){ if(r.top && r.group && S.groupBars) rule(S.medium,'Bar_Group'); else if(S.rowRules && (r.top||!S.groupBars)) rule(S.hair,'Hairline'); } drawRow(r); });
  }
  rule(S.heavy,'Bar_Heavy_Bottom');
  const flh=S.foot*S.lead;
  y += flh*0.15;
  panel.foot.forEach(t=>{ const segs=[{text:t,b:false,i:false}]; wrapSegs(f,segs,S.foot,inner,0).forEach(l=>{ y+=flh; items.push({t:'text',x:x0,y:y-flh*0.22,segs:l,size:S.foot,grp:'Footnotes'}); }); });
  y += pad;
  const H=y;
  items.unshift({t:'box',x:S.box/2,y:S.box/2,w:W-S.box,h:H-S.box,sw:S.box,grp:'Box'});
  // outside: other ingredients
  const oi=otherIngredients(p); const ext=[]; let ey=H+S.oiGap;
  if(S.showOI){
    const olh=S.oiSize*S.lead;
    if(oi.contains){ wrapSegs(f,[{text:oi.contains,b:true,i:false}],S.oiSize,W,0).forEach(l=>{ ey+=olh; ext.push({t:'text',x:0,y:ey-olh*0.22,segs:l,size:S.oiSize,grp:'Contains'}); }); }
    if(oi.items.length){ wrapSegs(f,[{text:T.oiLabel+' ',b:true,i:false},{text:oi.text,b:false,i:false}],S.oiSize,W,0).forEach(l=>{ ey+=olh; ext.push({t:'text',x:0,y:ey-olh*0.22,segs:l,size:S.oiSize,grp:'Other_Ingredients'}); }); }
  }
  return {W,H,items,ext,extH:ext.length?ey+2:H,rowY,panel,oi,f,tf,titleSize:ts,nameMax,amtRight,dvRight};
}
function checks(p, L){
  const S=p.style, out=[]; const add=(sev,msg,det,rowId,src)=>out.push({sev,msg,det,rowId,src});
  const area=num(p.pkg.area);
  let cat='standard', minBody=8, minSmall=6;
  if(area!=null && area<12){ cat='small'; minBody=4.5; minSmall=4.5; }
  else if(area!=null && area<=40){ cat='intermediate'; minBody=6; minSmall=6; }
  if(area==null) add('warn','Label area not set','Enter the area available for labeling to evaluate small-package type minimums.',null,'Package');
  else if(p.pkg.areaSource!=='dieline') add('info',`Package: ${cat} (${trim(area,1)} sq in, estimated)`,'Confirm the available labeling area against the dieline.',null,'Package');
  if(S.body<minBody) add('warn',`Body type ${S.body} pt is under the ${minBody} pt minimum`,`${cat==='standard'?'101.36(e)':'101.36(i)(2)'}: ${cat} package. Flagged, not enforced.`,null,'Type size');
  if(S.head<minSmall) add('warn',`Column heading ${S.head} pt is under ${minSmall} pt`,'Column headings and footnotes may be 6 pt on standard packages.',null,'Type size');
  if(S.foot<minSmall) add('warn',`Footnotes ${S.foot} pt are under ${minSmall} pt`,'',null,'Type size');
  const bigger = Math.max(S.body,S.head,S.foot);
  if(L.titleSize<=bigger) add('block','Title is not the largest type','"Supplement Facts" must be larger than all other print in the panel.',null,'Type size');
  const proc=PROCESS[p.pkg.process]||PROCESS.digital;
  [['hairline',S.hair],['box rule',S.box],['medium bar',S.medium]].forEach(([n,w])=>{ if(w>0 && w<proc.minRule) add('warn',`${n[0].toUpperCase()+n.slice(1)} ${w} pt is under the ${proc.label.toLowerCase()} minimum`,`Printer minimum set to ${proc.minRule} pt.`,null,'Print'); });
  const minText=Math.min(S.body,S.head,S.foot,S.oiSize);
  if(minText<proc.minType) add('warn',`Smallest type ${minText} pt is under the ${proc.label.toLowerCase()} limit`,`Process minimum ${proc.minType} pt.`,null,'Print');
  if(S.inverse) add('info','Reversed panel','Text and rules export as knockout (0/0/0/0). Check the minimum reversed type size with your printer.',null,'Print');
  // font
  const f=fontDef(p,'body');
  if(!fontAvailable(f.css) && !state.loadedFonts[f.name]) add('info',`${f.name} is not available to this browser`,'Preview and line breaks use fallback metrics. Load the font files under Style for exact widths; exported text still names the real font.',null,'Font');
  // macros
  const cal=p.macros.calories;
  if(cal && cal.status!=='verified' && num(cal.v)!=null && cal.v>=3.5 && cal.v<7.5) add('warn',`Calories (${trim(cal.v,1)} kcal) estimated near the 5 kcal cutoff`,'Declared as '+roundMacro('cal',cal.v)+'. Supplier data decides whether the line appears.','m_calories','Nutrition data');
  MACROS.forEach(m=>{ const e=p.macros[m.k]; if(!e) return; const rv=roundMacro(m.round,num(e.v)); if(e.show==='show' && (rv===0||e.v==null)) add('info',`${m.label} shown at zero`,'101.36 omits nutrients present at zero. Showing "0 g" is a common liberty (e.g. to advertise zero sugar).','m_'+m.k,'Liberty'); });
  // rows
  const vmSeen={}; const est=[];
  for(const r of p.rows){
    const nm = r.kind==='nutrient' ? (r.label||VMK[r.nk]?.label||'Nutrient') : plain(r.name||'Row');
    if(r.status==='estimated') est.push({nm,id:r.id});
    if(r.status==='missing') add('block',`${nm}: supplier data missing`,'',r.id,'Data');
    if(r.note) add(r.noteSev||'info', nm, r.note, r.id, 'Reviewer note');
    if(r.tm && r.tmStatus==='pending') add('warn',`${r.tm} styling not confirmed`,'Take styling from the TLA, the brand, or a TLA-reviewed product on market.',r.id,'Trademark');
    if(r.kind==='nutrient'){
      if(vmSeen[r.nk]) add('block',`${nm} listed twice`,'Combine sources into one line: "(as A and B)".',r.id,'Panel');
      vmSeen[r.nk]=1;
      const v=num(r.amt);
      if((r.nk==='sodium'||r.nk==='potassium') && v!=null && roundNaK(v)!==v){ if(p.text.naKRound) add('info',`${nm} rounded ${trim(v)} → ${roundNaK(v)} mg`,'Sodium/potassium rounding per 101.9(c): nearest 5 mg up to 140 mg, nearest 10 mg above.',r.id,'Rounding'); else add('warn',`${nm} printed unrounded (${trim(v)} mg)`,`101.9(c) rounding would give ${roundNaK(v)} mg. Rounding is switched off under Text.`,r.id,'Rounding'); }
      if(r.place==='other' && r.source && num(r.input)==null) add('warn',`${nm}: source weight missing`,'Needed to place the source in Other Ingredients.',r.id,'Other ingredients');
    }
    if(r.kind==='ingredient' && r.botanical){ const n=r.name||''; if(!/_[^_]+_/.test(n)) add('warn',`${nm}: Latin name missing`,'Botanicals need the Latin binomial (italicized: wrap in _underscores_).',r.id,'Botanical'); if(!/\b(root|leaf|leaves|bark|seed|fruit|flower|aerial|whole plant|husk|rhizome|berry|peel|stem|herb)\b/i.test(n)) add('warn',`${nm}: plant part missing`,'101.4(h) requires the part of the plant.',r.id,'Botanical'); }
    if(r.kind==='group'){
      const sum=groupSumMg(p,r.id);
      if(r.override){ const pa=parseAmt(r.override); if(pa){ const mg=toMg(pa.v,pa.u); if(Math.abs(mg-sum)>Math.max(0.5,sum*0.005)) add('block',`${plain(r.name)} total reads ${r.override}`,`Components add to ${fmtTotal(p,sum)}. Check the value and unit.`,r.id,'Blend math'); } }
      if(!childrenOf(p,r.id).length) add('warn',`${plain(r.name)} has no components`,'',r.id,'Blend math');
    }
    if(r.kind==='other'){
      if(num(r.input)==null) add('warn',`${nm}: weight missing`,'Listed last until a weight is entered; the order may be wrong.',r.id,'Other ingredients');
      if(r.cat==='flavor' && (!r.ftype || r.ftype==='unconfirmed')) add('warn',`${nm}: natural or artificial not confirmed`,'Item code does not say. Get the composition statement.',r.id,'Other ingredients');
    }
  }
  if(est.length>3) add('warn',`${est.length} inputs are estimates`,est.map(e=>e.nm).join(', ')+'. Replace with supplier spec or COA values.',null,'Data');
  else est.forEach(e=>add('warn',`${e.nm}: data estimated`,'Replace with supplier spec or COA values.',e.id,'Data'));
  const oi=L.oi; const flavN=p.rows.filter(r=>r.kind==='other'&&r.cat==='flavor').length;
  if(flavN>1) { const it=oi.items.find(i=>i.flavor); if(it) add('info',`${flavN} flavors grouped as "${it.name}"`,`Placed by combined weight (${trim(it.w||0,1)} mg).`,null,'Other ingredients'); }
  if(!p.allergensReviewed) add('warn','Allergens not reviewed','Check composition statements (flavors, carriers, branded botanicals) and mark reviewed under Product.',null,'Allergens');
  if(p.serving.showSpc && String(p.serving.spc)==='1') add('info','"Servings Per Container 1" shown','May be omitted on a single-serving container when net contents states it.',null,'Panel');
  const su=suggestedUse(p); if(su.missing.length) add('warn','Suggested use incomplete',`Missing: ${su.missing.join(', ')}.`,null,'Text');
  const caf=totalCaffeine(p); if(caf.n>1) add('info',`Total caffeine ${caf.mg} mg from ${caf.n} sources`,'Use this total for caffeine callouts and statements.',null,'Callouts');
  // text chars
  const bad=new Set(); const scan=s=>{ for(const ch of s){ if(!winAnsiCode(ch)) bad.add(ch); } };
  L.items.concat(L.ext).forEach(it=>{ if(it.t==='text') it.segs.forEach(sg=>scan(sg.text)); });
  if(bad.size) add('warn','Characters outside the PDF text encoding',`${[...bad].join(' ')}: these export as "?" in the PDF (SVG is fine).`,null,'Export');
  (p.flags||[]).forEach(fl=>add(fl.sev,fl.msg,fl.det,null,'Co-man review'));
  const order={block:0,warn:1,info:2}; out.sort((a,b)=>order[a.sev]-order[b.sev]);
  return out;
}

/* ---------- output ---------- */
function svgFor(p, L, opts={}){
  const S=p.style; const ink = S.inverse?'#FFFFFF':'#000000';
  const forExport = !!opts.export; const withExt = opts.ext!==false && S.showOI;
  const Hall = withExt ? L.extH : L.H;
  const f=L.f, tf=L.tf;
  const fam=(font,seg)=>{ const k=seg.b&&seg.i?'bi':seg.b?'b':seg.i?'i':'r'; return font.ps[k]; };
  const txt=(it)=>{
    const font = it.font==='title'?tf:f;
    const anchor = it.anchor==='end'?' text-anchor="end"':'';
    if(forExport){
      const spans = it.segs.map(s=>`<tspan font-family="${esc(fam(font,s))}">${esc(s.text)}</tspan>`).join('');
      return `<text x="${trim(it.x)}" y="${trim(it.y)}" font-size="${trim(it.size)}" fill="${ink}"${anchor} xml:space="preserve">${spans}</text>`;
    }
    const spans = it.segs.map(s=>`<tspan font-weight="${s.b?700:400}" font-style="${s.i?'italic':'normal'}">${esc(s.text)}</tspan>`).join('');
    return `<text x="${trim(it.x)}" y="${trim(it.y)}" font-size="${trim(it.size)}" fill="${ink}" font-family='${esc(font.css+FALLBACK)}'${anchor} xml:space="preserve">${spans}</text>`;
  };
  const groups=new Map(); const orderK=[];
  const put=(g,s)=>{ if(!groups.has(g)){groups.set(g,[]);orderK.push(g);} groups.get(g).push(s); };
  L.items.forEach(it=>{
    if(it.t==='box') put('Box',`<rect x="${trim(it.x)}" y="${trim(it.y)}" width="${trim(it.w)}" height="${trim(it.h)}" fill="none" stroke="${ink}" stroke-width="${trim(it.sw)}"/>`);
    else if(it.t==='rect') put(it.grp,`<rect x="${trim(it.x)}" y="${trim(it.y)}" width="${trim(it.w)}" height="${trim(it.h)}" fill="${ink}"/>`);
    else put(it.grp, txt(it));
  });
  let seen={}; const gid=g=>{ seen[g]=(seen[g]||0)+1; return seen[g]>1?`${g}_${seen[g]}`:g; };
  // hairlines/bars share names; merge rules into one "Rules" group for tidy layers
  let body='';
  const ruleG=[]; const textG=[];
  orderK.forEach(k=>{ const c=groups.get(k).join(''); if(/^Bar_|^Hairline|^Box/.test(k)) ruleG.push(`<g id="${gid(k)}">${c}</g>`); else textG.push(`<g id="${gid(k)}">${c}</g>`); });
  body = `<g id="Supplement_Facts"><g id="Rules">${ruleG.join('')}</g><g id="Text">${textG.join('')}</g></g>`;
  if(withExt && L.ext.length){ const eg=new Map(); L.ext.forEach(it=>{ if(!eg.has(it.grp)) eg.set(it.grp,[]); eg.get(it.grp).push(txt(it)); }); body += `<g id="Outside_Panel">${[...eg].map(([k,v])=>`<g id="${k}">${v.join('')}</g>`).join('')}</g>`; }
  let overlay='';
  if(!forExport && state.overlay && opts.flags){
    const marks={}; opts.flags.forEach((fl,i)=>{ if(fl.rowId && L.rowY[fl.rowId]!=null && fl.sev!=='info'){ (marks[fl.rowId]=marks[fl.rowId]||[]).push({n:i+1,sev:fl.sev}); } });
    Object.entries(marks).forEach(([rid,arr])=>{ const y=L.rowY[rid]; arr.slice(0,3).forEach((m,j)=>{ const cx=L.W+7+j*9.5; const col=m.sev==='block'?'#B0271F':'#C98200'; overlay+=`<g class="mk" data-row="${esc(rid)}" style="cursor:pointer"><circle cx="${cx}" cy="${y}" r="4.2" fill="${col}"/><text x="${cx}" y="${y+1.6}" font-size="4.4" text-anchor="middle" fill="#fff" font-family="IBM Plex Mono, monospace">${m.n}</text></g>`; }); });
  }
  const pad = forExport?0:0;
  const vbW = forExport ? L.W : L.W + (overlay?34:0);
  const z = opts.zoom||1;
  const size = forExport ? `width="${trim(L.W)}pt" height="${trim(Hall)}pt"` : `width="${trim(vbW*z)}" height="${trim(Hall*z)}"`;
  return `<svg xmlns="http://www.w3.org/2000/svg" ${size} viewBox="0 0 ${trim(vbW)} ${trim(Hall)}">${forExport?`<title>Supplement Facts - ${esc(p.name)}</title>`:''}${body}${overlay}</svg>`;
}
const WIN = {0x20AC:0x80,0x201A:0x82,0x0192:0x83,0x201E:0x84,0x2026:0x85,0x2020:0x86,0x2021:0x87,0x02C6:0x88,0x2030:0x89,0x0160:0x8A,0x2039:0x8B,0x0152:0x8C,0x017D:0x8E,0x2018:0x91,0x2019:0x92,0x201C:0x93,0x201D:0x94,0x2022:0x95,0x2013:0x96,0x2014:0x97,0x02DC:0x98,0x2122:0x99,0x0161:0x9A,0x203A:0x9B,0x0153:0x9C,0x017E:0x9E,0x0178:0x9F};
const WIN_REV = Object.fromEntries(Object.entries(WIN).map(([u,c])=>[c,+u]));
function winAnsiCode(ch){ const u=ch.codePointAt(0); if(u>=32&&u<127) return u; if(u>=160&&u<=255) return u; return WIN[u]||0; }
function pdfStr(s){ let o=''; for(const ch of s){ let c=winAnsiCode(ch)||63; if(c===40||c===41||c===92) o+='\\'+String.fromCharCode(c); else if(c<32||c>126) o+='\\'+c.toString(8).padStart(3,'0'); else o+=String.fromCharCode(c); } return '('+o+')'; }
function pdfFor(p, L, withExt){
  const S=p.style; const k = S.inverse?'0 0 0 0':'0 0 0 1';
  const H = withExt?L.extH:L.H; const W=L.W;
  const fontsUsed=new Map(); // ps -> {res, font, seg}
  const fk=(font,seg)=>{ const key=seg.b&&seg.i?'bi':seg.b?'b':seg.i?'i':'r'; const ps=font.ps[key]; if(!fontsUsed.has(ps)) fontsUsed.set(ps,{res:'F'+(fontsUsed.size+1), font, b:!!seg.b, i:!!seg.i}); return fontsUsed.get(ps).res; };
  let c=`% Supplement Facts - ${p.name.replace(/[^\x20-\x7e]/g,'')}\n${k} k ${k} K\n`;
  const all = withExt ? L.items.concat(L.ext) : L.items;
  for(const it of all){
    if(it.t==='box'){ c+=`${trim(it.sw)} w ${trim(it.x)} ${trim(H-it.y-it.h)} ${trim(it.w)} ${trim(it.h)} re S\n`; }
    else if(it.t==='rect'){ c+=`${trim(it.x)} ${trim(H-it.y-it.h)} ${trim(it.w)} ${trim(it.h)} re f\n`; }
    else {
      const font = it.font==='title'?L.tf:L.f;
      const w = measureSegs(font,it.segs,it.size);
      const x = it.anchor==='end' ? it.x - w : it.x;
      c+=`BT 1 0 0 1 ${trim(x)} ${trim(H-it.y)} Tm `;
      it.segs.forEach(sg=>{ c+=`/${fk(font,sg)} ${trim(it.size)} Tf ${pdfStr(sg.text)} Tj `; });
      c+='ET\n';
    }
  }
  const objs=[]; const add=s=>{ objs.push(s); return objs.length; };
  const catalogId=add(null), pagesId=add(null), pageId=add(null);
  const contentId=add(`<< /Length ${c.length} >>\nstream\n${c}endstream`);
  const fontRefs=[];
  for(const [ps,info] of fontsUsed){
    const widths=[]; for(let code=32;code<=255;code++){ const u = (code>=0x80&&code<=0x9F)? (WIN_REV[code]||32) : code; widths.push(Math.round(measure(info.font,{text:String.fromCodePoint(u),b:info.b,i:info.i},1000))); }
    const flags = 32 + (info.i?64:0);
    const fd=add(`<< /Type /FontDescriptor /FontName /${ps} /Flags ${flags} /FontBBox [-200 -250 1200 950] /ItalicAngle ${info.i?-11:0} /Ascent 750 /Descent -250 /CapHeight 674 /StemV ${info.b?140:88} >>`);
    const fid=add(`<< /Type /Font /Subtype /Type1 /BaseFont /${ps} /Encoding /WinAnsiEncoding /FirstChar 32 /LastChar 255 /Widths [${widths.join(' ')}] /FontDescriptor ${fd} 0 R >>`);
    fontRefs.push(`/${info.res} ${fid} 0 R`);
  }
  objs[catalogId-1]=`<< /Type /Catalog /Pages ${pagesId} 0 R >>`;
  objs[pagesId-1]=`<< /Type /Pages /Kids [${pageId} 0 R] /Count 1 >>`;
  objs[pageId-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${trim(W)} ${trim(H)}] /TrimBox [0 0 ${trim(W)} ${trim(H)}] /Resources << /Font << ${fontRefs.join(' ')} >> >> /Contents ${contentId} 0 R >>`;
  const infoId=add(`<< /Title ${pdfStr('Supplement Facts - '+p.name)} /Producer (NutraPack Panel Builder) >>`);
  let out='%PDF-1.4\n%\xE2\xE3\xCF\xD3\n'; const offs=[];
  objs.forEach((o,i)=>{ offs.push(out.length); out+=`${i+1} 0 obj\n${o}\nendobj\n`; });
  const xref=out.length;
  out+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`+offs.map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('');
  out+=`trailer\n<< /Size ${objs.length+1} /Root ${catalogId} 0 R /Info ${infoId} 0 R >>\nstartxref\n${xref}\n%%EOF`;
  const bytes=new Uint8Array(out.length); for(let i=0;i<out.length;i++) bytes[i]=out.charCodeAt(i)&255;
  return bytes;
}
function fileBase(p){ return (p.name||'panel').replace(/[—–]/g,'-').replace(/[^A-Za-z0-9 _-]+/g,'').trim().replace(/\s+/g,'_').slice(0,60)||'panel'; }

/* ---------- import ---------- */
const imp = { step:'pick', file:null, kind:null, template:'auto', items:null, lines:null, detected:null, wb:null, sheet:null, grid:null, map:null, headerRow:0, profile:'', header:{}, rows:[], specOther:null, error:'' };
async function pdfItems(buf){
  await needLib('pdf');
  const lib=window.pdfjsLib; lib.GlobalWorkerOptions.workerSrc=LIBS.pdf[0];
  const doc=await lib.getDocument({data:buf}).promise; const items=[];
  for(let p=1;p<=doc.numPages;p++){
    const page=await doc.getPage(p); const vp=page.getViewport({scale:1}); const tc=await page.getTextContent();
    tc.items.forEach(it=>{ if(!it.str || !it.str.trim()) return; items.push({p:p-1, x:it.transform[4], y:vp.height-it.transform[5], s:it.str}); });
  }
  return items;
}
function buildLines(items){
  const sorted=items.slice().sort((a,b)=>a.p-b.p || a.y-b.y || a.x-b.x);
  const L=[];
  for(const it of sorted){ const last=L[L.length-1]; if(last && last.p===it.p && Math.abs(last.y-it.y)<2.5) last.c.push(it); else L.push({p:it.p,y:it.y,c:[it]}); }
  const out=[]; let prev=null;
  for(const l of L){ l.c.sort((a,b)=>a.x-b.x); const text=l.c.map(c=>c.s.trim()).join(' ').replace(/\s+/g,' ').trim(); if(!text) continue;
    if(prev && prev.p===l.p && prev.text===text && Math.abs(prev.y-l.y)<20) continue; // duplicated faux-bold runs
    const o={p:l.p,y:l.y,text}; out.push(o); prev=o; }
  return out;
}
const numv = s=>{ if(s==null) return null; const n=parseFloat(String(s).replace(/,/g,'')); return Number.isFinite(n)?n:null; };
function firstMatch(lines, re){ for(const l of lines){ const m=l.text.match(re); if(m) return m; } return null; }
function block(lines, startRe, endRe){ const i=lines.findIndex(l=>startRe.test(l.text)); if(i<0) return null; const out=[]; for(let j=i+1;j<lines.length;j++){ if(endRe.test(lines[j].text) || lines[j].p!==lines[i].p) break; out.push(lines[j].text); } return out.join(' ').trim(); }
const TEMPLATES = {
  acb:{ label:'ACB quote (Arizona Custom Blends)', detect:t=>/ARIZONA CUSTOM BLENDS|ACB Formula #|acbmfg\.com/i.test(t) && /Claimed Ingredient/i.test(t),
    parse(lines){
      const rows=[]; let nonActive=false;
      for(const l of lines){
        if(/Non-Active Ingredients/i.test(l.text)){ nonActive=true; continue; }
        const m=l.text.match(/^(R\d{4,6})\s+(.+?)\s+(No|Yes)\s+([\d.,]+)\s+(mcg|mg|g|IU)\s+([\d.]+)\s+([\d.]+)\s+([\d.,]+)$/i);
        if(m){ const claim=numv(m[4]); if(!claim) continue; rows.push({code:m[1], name:m[2].trim(), claim, unit:m[5].toLowerCase(), potency:numv(m[6]), overage:numv(m[7]), input:numv(m[8]), custSupplied:m[3]==='Yes', forceOther:nonActive, raw:l.text}); }
      }
      const h={};
      let m=firstMatch(lines,/Product:\s*(.+?)\s+ACB Formula #\s*(\d+)/i); if(m){ h.product=m[1]; h.formula=m[2]; }
      m=firstMatch(lines,/Number:\s*(\d+)\s+Revision#?\s*(\d+)/i); if(m){ h.quote=m[1]; h.rev=m[2]; }
      m=firstMatch(lines,/Company Name:\s*(.+)$/i); if(m) h.client=m[1].trim();
      m=firstMatch(lines,/PRODUCT INFORMATION FOR\s+(\w+)/i); if(m) h.form=/powder/i.test(m[1])?'powder':/capsule|tablet|softgel/i.test(m[1])?'capsule':/liquid/i.test(m[1])?'liquid':'powder';
      m=firstMatch(lines,/Grams per (Sachet|Stick|Serving|Scoop)\s+([\d.]+)/i); if(m){ h.weight=numv(m[2]); h.unit=/sachet/i.test(m[1])?'Sachet':/stick/i.test(m[1])?'Stick Pack':''; }
      m=firstMatch(lines,/Net Weight per serving \(mg\):\s*([\d.,]+)/i); if(m && !h.weight) h.weight=+(numv(m[1])/1000).toFixed(2);
      m=firstMatch(lines,/Size:\s*([\d.]+)\s*w\s*x\s*([\d.]+)\s*h/i); if(m) h.labelSize=`${m[1]} × ${m[2]} in`;
      m=firstMatch(lines,/(Sachets|Sticks) per Retail Box:?\s*(\d+)/i); if(m) h.perBox=m[2];
      m=firstMatch(lines,/Date:\s*([\d/]+)/i); if(m) h.date=m[1];
      h.coman='Arizona Custom Blends (ACB)';
      h.ref=[h.quote&&`Quote ${h.quote}${h.rev?' Rev '+h.rev:''}`, h.formula&&`Formula ${h.formula}`, h.date].filter(Boolean).join(' · ');
      if(h.form==='powder'){ h.qty='1'; h.unit=h.unit||'Serving'; h.spc='1'; h.showSpc=false; }
      return {rows, header:h, specOther:null};
    }},
  veritacor:{ label:'Veritacor finished product spec', detect:t=>/Finish Product Specification Formulation/i.test(t),
    parse(lines){
      const rows=[];
      for(const l of lines){
        if(l.p>0) break;
        const m=l.text.match(/^(.+?)\s+(\d+\.\d{2})%\s+([\d.,]+)\s*(mcg|mg|g)\s+(\d+(?:\.\d+)?)%\s+(.*)$/i);
        if(!m) continue; const name=m[1].trim(); const claim=numv(m[3]); if(name==='0' || !claim) continue;
        const nums=m[6].split(/\s+/).filter(t=>/^[\d.,]+$/.test(t)).map(numv);
        rows.push({name, claim, unit:m[4].toLowerCase(), potency:numv(m[2]), overage:numv(m[5]), input:nums[1]??nums[0]??null, raw:l.text});
      }
      const h={coman:'Veritacor'};
      let m=firstMatch(lines,/Product Description:\s*(.+?)\s+# Units/i); if(m) h.product=m[1];
      m=firstMatch(lines,/(?:Number )?Servings:?\s+(\d+)\b/i); if(m) h.spc=m[1];
      m=firstMatch(lines,/Customer:?\s+(.+?)\s+(?:Capsules|Customer|Tablets|Softgels|Scoops)/i); if(m) h.client=m[1];
      m=firstMatch(lines,/(Capsules|Tablets|Softgels)\/Servings?:?\s+(\d+)/i); if(m){ h.qty=m[2]; h.unit=m[1][0].toUpperCase()+m[1].slice(1).toLowerCase(); h.form='capsule'; }
      m=firstMatch(lines,/(?:Capsules|Tablets|Softgels) (?:Per|per) Container\s+(\d+)|(?:Capsules|Tablets|Softgels)\/Container\s+(\d+)/i); if(m) h.count=m[1]||m[2];
      m=firstMatch(lines,/Date:\s*([\d/]+)/i); if(m) h.date=m[1];
      m=firstMatch(lines,/Version #\s*(\w+)/i); if(m) h.version=m[1];
      h.ref=[h.version&&`Spec Ver ${h.version}`, h.date].filter(Boolean).join(' · ');
      if(!h.form) h.form='powder';
      h.showSpc=true;
      const other=block(lines,/^Other Ingredients:?$/i,/^(Label Claims|Capsule Information|Allergens|5\. Testing)/i);
      const allergens=block(lines,/^Allergens:?$/i,/^Other Ingredients/i);
      if(allergens) h.allergens=allergens;
      m=firstMatch(lines,/^Capsule\s+(.+?)\s+([\d,.]+)\s+[\d,.]+$/i);
      if(m){ const desc=m[1]; const sz=(desc.match(/Size\s*(000|00|0|1|2|3|4)\b/i)||[])[1]; const veg=/veg|hpmc|hypromellose|plant/i.test(desc); h.capsule={desc, size:sz, veg, per:numv(h.qty)||1, mg:sz!=null?CAPSULE_MG[sz]:null}; }
      return {rows, header:h, specOther: other===null?null:other};
    }},
  generic:{ label:'Generic table (any PDF)', detect:()=>true,
    parse(lines){
      const rows=[];
      for(const l of lines){
        if(/total|net weight|batch|price|\$|serving size|servings per|date:|phone|email/i.test(l.text)) continue;
        const m=l.text.match(/^([A-Za-z][^\d]*?(?:\d+:\d+|\d+%[^\d]*?)?)\s+([\d.,]+)\s*(mcg|mg|g|IU)\b(.*)$/i);
        if(!m) continue; const claim=numv(m[2]); if(!claim) continue;
        const pot=(m[4].match(/([\d.]+)%/)||[])[1];
        rows.push({name:m[1].trim(), claim, unit:m[3].toLowerCase(), potency:pot?numv(pot):null, overage:null, input:null, raw:l.text});
      }
      return {rows, header:{}, specOther:null};
    }}
};
const NUT_RE = [
  [/methylcobalamin|cyanocobalamin|adenosylcobalamin|hydroxocobalamin|vitamin b-?12\b/i,'vitB12'],[/pyridox|vitamin b-?6\b/i,'vitB6'],
  [/folate|folic acid|methylfolate|methyltetrahydrofolate/i,'folate'],[/thiamin|vitamin b-?1\b/i,'thiamin'],[/riboflavin|vitamin b-?2\b/i,'riboflavin'],
  [/niacin|nicotinamide|vitamin b-?3\b/i,'niacin'],[/pantothen|vitamin b-?5\b/i,'pantothenic'],[/biotin/i,'biotin'],
  [/ascorbic|ascorbate|vitamin c\b/i,'vitC'],[/cholecalciferol|ergocalciferol|vitamin d/i,'vitD'],[/tocopher|vitamin e\b/i,'vitE'],
  [/phylloquinone|menaquinone|vitamin k/i,'vitK'],[/retinyl|retinol|vitamin a\b/i,'vitA'],[/\bcholine\b/i,'choline'],
  [/chromium/i,'chromium'],[/selen/i,'selenium'],[/molybd/i,'molybdenum'],[/iodine|iodide|kelp/i,'iodine'],[/\bzinc\b/i,'zinc'],
  [/copper|cupric/i,'copper'],[/mangan/i,'manganese'],[/\biron\b|ferrous|ferric/i,'iron'],[/magnesium/i,'magnesium'],[/calcium/i,'calcium'],
  [/potassium/i,'potassium'],[/\bsodium\b|\bsalt\b/i,'sodium'],[/chloride/i,'chloride'],[/phosph/i,'phosphorus']
];
const OTHER_RE = [
  ['capsule',/capsule|hypromellose|\bhpmc\b|gelatin|pullulan/i],
  ['flavor',/flavou?r/i],
  ['color',/\bcolou?r\b|fd&c|red (no\.? ?)?40|blue (no\.? ?)?1\b|yellow (no\.? ?)?[56]\b|\bbeet\b|carmine|annatto|caramel color|titanium dioxide|beta.?carotene/i],
  ['sweetener',/sucralose|stevia|\breb[\s-]?[a-m]\b|rebaudioside|acesulfame|ace-k|monk ?fruit|luo han|erythritol|xylitol|allulose|\bsugar\b|dextrose|sucrose|aspartame|thaumatin/i],
  ['acid',/citric acid|malic acid|tartaric acid|lactic acid|fumaric acid|adipic acid|phosphoric acid/i],
  ['preservative',/sorbate|benzoate/i],
  ['excipient',/stearate|stearic|silicon dioxide|\bsilica\b|rice flour|rice extract|cellulose|maltodextrin|calcium silicate|tricalcium phosphate|dicalcium phosphate|croscarmellose|\bgum\b|lecithin|glycerin|starch|\btalc\b|shellac|\bmct\b|inulin|dextrin|xanthan|guar|acacia|carrageenan|alginate|bicarbonate|magnesium silicate/i]
];
const NOT_BOTANICAL=/creatine|alanine|citrulline|arginine|tyrosine|glutamine|taurine|carnitine|lipoic|betaine|caffeine|malate|gpc|glycine|leucine|valine/i;
const titleFirst=s=>s.replace(/\b([a-z])/g,(m,c)=>c.toUpperCase());
function classify(r){
  const name=r.name; const pot=r.potency;
  const out={include:true, note:'', noteSev:'info'};
  let oc=null; for(const [c,re] of OTHER_RE){ if(re.test(name)){ oc=c; break; } }
  if(r.forceOther && !oc) oc='excipient';
  // nutrient?
  let nk=null; for(const [re,k] of NUT_RE){ if(re.test(name)){ nk=k; break; } }
  const startsWithNut = nk && new RegExp('^\\s*'+VMK[nk].label.split(' ')[0],'i').test(name);
  const isNutrient = nk && !oc && (startsWithNut || (pot!=null && pot<100) || /vitamin/i.test(name));
  if(isNutrient){
    out.role='n:'+nk;
    let src='', conn='as', tm='';
    const tmm=name.match(/\(([^()]*[®™][^()]*)\)/); if(tmm) tm=tmm[1].trim();
    const asm=name.match(/\((as|from)\s+([^)]+)\)/i);
    if(asm){ conn=asm[1].toLowerCase(); src=asm[2]; }
    else if(startsWithNut){ const pm=name.match(/\(([^)]+)\)/); if(pm && pm[1]!==tm) src=pm[1]; else if(name.replace(/\(.*?\)/g,'').trim().toLowerCase()!==VMK[nk].label.toLowerCase()) src=name.replace(/\s*\([^)]*\)/g,''); }
    else src=name;
    src=src.replace(/\s*\d+(\.\d+)?\s*%/g,'').replace(/\s*\([^)]*[®™][^)]*\)/g,'').trim();
    if(tm && src && !src.includes(tm)) src=tm+' '+src;
    out.source=src; out.conn=conn; out.tm=tm;
    const def=VMK[nk]; let claim=r.claim, unit=r.unit;
    if(def.unit==='mcg' && unit==='mg' && claim<1){ claim=+(claim*1000).toFixed(3); unit='mcg'; }
    if(nk==='folate') unit='mcg DFE';
    out.claim=claim; out.unit=unit;
    if(pot===100 && !startsWithNut) { out.note='Potency is 100%: check whether the claim is the elemental nutrient or the whole compound.'; out.noteSev='warn'; }
    if(tm) { out.note=(out.note?out.note+' ':'')+`Trademark "${tm}" found: confirm styling with the TLA.`; out.noteSev=out.noteSev==='warn'?'warn':'warn'; }
    if(nk==='folate' && /folic/i.test(name)){ out.note=(out.note?out.note+' ':'')+'Folic acid: DFE = mcg folic acid × 1.7.'; out.noteSev='warn'; }
    return out;
  }
  if(oc){
    out.role='o:'+oc; out.claim=r.claim; out.unit=r.unit;
    let nm=name;
    if(oc==='flavor'){ const nat=/\bnat(ural)?\b/i.test(name), art=/\bart(ificial)?\b|\bN\s?&\s?A\b/i.test(name); out.ftype= nat&&art?'nat_art':nat?'natural':art?'artificial':'unconfirmed';
      nm=name.replace(/^flavou?r\s*[-–:]\s*/i,'').trim(); if(!/flavou?r/i.test(nm)) nm=nm+' Flavor'; }
    if(oc==='sweetener' && /reb\s?m/i.test(name) && /stevia/i.test(name)){ nm='Stevia Leaf Extract (Reb M)'; out.note='Confirm Reb M name with the supplier (leaf extract vs. bioconversion).'; out.noteSev='warn'; }
    out.oname=nm;
    return out;
  }
  out.role='d'; out.claim=r.claim; out.unit=r.unit;
  let nm=name;
  if(out.claim<1 && out.unit==='mg'){ out.claim=+(out.claim*1000).toFixed(3); out.unit='mcg'; }
  if(out.claim>=1000 && out.unit==='mg' && out.claim%100===0){ out.claim=out.claim/1000; out.unit='g'; }
  out.caff = /dicaffeine malate/i.test(name)?74 : /caffeine citrate/i.test(name)?50 : /caffeine/i.test(name)?100 : null;
  out.botanical = /extract|root|leaf|leaves|bark|seed|fruit|herb|husk|berry|rhizome|flower|powder/i.test(name) && !NOT_BOTANICAL.test(name);
  const namePct=(name.match(/(\d+(?:\.\d+)?)\s*%/)||[])[1];
  if(namePct && pot===100 && !/std\.?|standardi[sz]ed/i.test(name)) { out.note=`Name says ${namePct}% but potency is 100%. Is the claim the raw material or the active?`; out.noteSev='block'; }
  else if(pot!=null && pot<100){ out.note=`Potency ${pot}%: the claim looks like the active marker, not the ingredient weight. Confirm how it should be declared.`; out.noteSev='warn'; }
  if(out.botanical){ out.note=(out.note?out.note+' ':'')+'Add the Latin name (_italic_) and plant part.'; if(out.noteSev==='info') out.noteSev='warn'; }
  out.dname=nm;
  return out;
}
function prepRows(raw){
  return raw.map(r=>{ const c=classify(r);
    const open=(r.name.match(/\(/g)||[]).length, close=(r.name.match(/\)/g)||[]).length;
    if(open!==close){ c.note=(c.note?c.note+' ':'')+'Name looks cut off in the spec (unbalanced parentheses).'; if(c.noteSev==='info') c.noteSev='warn'; } return Object.assign({}, r, c, {id:uid()}); });
}
function normName(s){ return String(s||'').toLowerCase().replace(/\(.*?\)/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\bflavors?\b/,'flavor').trim(); }
function setPdfLines(lines){
  imp.lines=lines; const all=lines.map(l=>l.text).join('\n');
  imp.detected = TEMPLATES.acb.detect(all)?'acb':TEMPLATES.veritacor.detect(all)?'veritacor':'generic'; imp.autoDetected=imp.detected!=='generic';
}
function toReview(){
  if(imp.kind==='pdf'){ const parsed=TEMPLATES[imp.detected].parse(imp.lines); imp.header=parsed.header; imp.specOther=parsed.specOther; imp.rows=prepRows(parsed.rows); }
  else {
    if(imp.profile){ const pr=loadProfiles(); pr[imp.profile]={sig:headerSig(imp.grid,imp.headerRow), map:imp.map, headerRow:imp.headerRow}; saveProfiles(pr); }
    imp.header={product:imp.file.name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' '), coman:imp.profile}; imp.specOther=null; imp.rows=prepRows(sheetRows());
  }
  imp.step='review'; renderImport();
}
function createFromImport(){
  const h=imp.header; const p=blankProject();
  p.name = h.product || (imp.file?imp.file.name.replace(/\.[^.]+$/,''):'Imported product');
  p.coman=h.coman||imp.profile||''; p.client=h.client||''; p.ref=[h.ref, imp.file&&imp.file.name].filter(Boolean).join(' · ');
  p.form=h.form||p.form;
  p.serving={qty:h.qty||(p.form==='powder'?'1':'2'), unit:h.unit||(p.form==='powder'?'Serving':'Capsules'), weight:h.weight||null, pattern:h.weight?'unit_weight':'unit', spc:h.spc||'', showSpc:h.showSpc!==false};
  p.suggested={qty:`${p.serving.qty} ${String(p.serving.unit).toLowerCase()}`.trim(), liquid:'', timing:'', freq:p.form==='powder'?'':'daily', override:''};
  const flags=[];
  if(p.form==='powder'){ p.style.widthIn=2.1; }
  const rows=[];
  for(const r of imp.rows){
    if(!r.include) continue;
    const [k,sub]=r.role.split(':');
    const common={status:'verified', note:r.note||'', noteSev:r.noteSev||'info', input:r.input??null, allergen:''};
    if(k==='n') rows.push(R(Object.assign(common,{kind:'nutrient', nk:sub, amt:r.claim, unit:r.unit, source:r.source||'', conn:r.conn||'as', place:'panel', tm:r.tm||'', tmStatus:r.tm?'pending':'n/a'})));
    else if(k==='d') rows.push(R(Object.assign(common,{kind:'ingredient', name:r.dname||r.name, amt:r.claim, unit:r.unit, parent:'', caff:r.caff||null, botanical:!!r.botanical})));
    else rows.push(R(Object.assign(common,{kind:'other', name:r.oname||r.name, cat:sub, ftype:sub==='flavor'?(r.ftype||'unconfirmed'):undefined, input:r.input??(r.unit==='mg'?r.claim:null)})));
  }
  if(h.capsule){
    const c=h.capsule; const nm = c.veg?'Vegetable Capsule':'Gelatin Capsule';
    if(!rows.some(r=>r.kind==='other' && r.cat==='capsule')) rows.push(R({kind:'other', name:nm, cat:'capsule', input:c.mg!=null?+(c.mg*c.per).toFixed(0):null, status:'estimated', note:`From packaging "${c.desc}". ${c.mg!=null?`${c.per} × ~${c.mg} mg size ${c.size} shell assumed.`:'Capsule size unknown.'} Confirm the shell weight.`, noteSev:'warn'}));
  }
  p.rows=rows;
  if(h.allergens){ p.allergensReviewed=false; flags.push({sev:'info', msg:`Spec allergens: ${h.allergens}`, det:'Confirm against composition statements.'}); }
  if(h.labelSize) flags.push({sev:'warn', msg:`Label size on spec: ${h.labelSize}`, det:'Enter the area available for labeling from the dieline to set type minimums.'});
  if(h.perBox) flags.push({sev:'info', msg:`${h.perBox} units per retail box`, det:'The carton panel needs its own servings per container and net contents.'});
  if(imp.specOther!==null){
    const spec=(imp.specOther||'').replace(/\.$/,'').split(/\s*,\s*/).filter(Boolean);
    const gen=otherIngredients(p).items.map(i=>i.name);
    if(!spec.length) flags.push({sev:'block', msg:'Spec "Other Ingredients" field is blank', det:`Generated from the formula: ${gen.join(', ')||'none'}.`});
    else {
      const gN=gen.map(normName), sN=spec.map(normName);
      const extra=spec.filter((s,i)=>!gN.includes(sN[i])); const missing=gen.filter((g,i)=>!sN.includes(gN[i]));
      if(extra.length) flags.push({sev:'block', msg:`Spec Other Ingredients lists ${extra.map(x=>`"${x}"`).join(', ')}`, det:'Not in the formula. Left out until the co-man confirms.'});
      if(missing.length) flags.push({sev:'warn', msg:`Spec Other Ingredients omits ${missing.join(', ')}`, det:'These are in the formula.'});
      const common=gN.filter(x=>sN.includes(x)); const specOrder=sN.filter(x=>gN.includes(x));
      if(common.join('|')!==specOrder.join('|')) flags.push({sev:'warn', msg:'Spec Other Ingredients order differs from weight order', det:`Spec: ${spec.join(', ')}. By weight: ${gen.join(', ')}.`});
    }
  }
  flags.push({sev:'info', msg:`Imported with ${imp.kind==='pdf'?TEMPLATES[imp.detected].label:'column mapping'+(imp.profile?` "${imp.profile}"`:'')}`, det:'Review every row against the source document before release.'});
  if(p.rows.some(r=>r.kind!=='other') ) flags.push({sev:'warn', msg:'Calories and macronutrients not on the spec', det:'Enter supplier nutrition data under Product, or confirm they fall below declaration thresholds.'});
  p.flags=flags;
  state.projects.push(p); state.cur=state.projects.length-1; state.tab='formula'; state.open=null;
  closeImport(); renderAll(); toast('Project created from '+(imp.file?imp.file.name:'import'));
}

/* ---------- app bridge (Update from spec…) ---------- */
function clone(o){ return JSON.parse(JSON.stringify(o)); }
function mergeImport(base, imported){
    var m = clone(base);
    ["form","serving","rows","flags","suggested","ref","coman"].forEach(function(k){
      if (imported[k] !== undefined) m[k] = clone(imported[k]);
    });
    if (!m.client && imported.client) m.client = imported.client;
    if (!m.name || m.name === "Untitled product") m.name = imported.name;
    m.allergensReviewed = false;                          // new formula → review allergens again
    m.id = base.id;
    return m;
  }

/* ---------- exports ---------- */
export const engine = {
  state, imp, P, pdfItems, buildLines, setPdfLines, toReview, createFromImport, TEMPLATES,
  layout, checks, svgFor, pdfFor, fileBase, mergeImport, blankProject, baseText, baseStyle, fontDef, FONTS,
};
export const SOURCE_HASH = "da1a3e4a182f6bdd";
